### ISSUE TITLE
训练voc数据集，没有预测框的问题

### ISSUE THREAD

**Issue by theDeep1nteresting** [bubbliiiing/yolox-pytorch#12]
首先感谢博主分享，
问题：使用你的yoloV4，yoloX的Code，根据教程，训练了voc数据集。模型可以正常训练，损失也在下降，可是模型加载新训练的权重后，预测结果没有预测框，这是什么问题呢？（直接使用你提供的权重就有训练框）我得pytorch版本是1.8.1 CUDA11.1

**Comment by theDeep1nteresting** [comment]
你好，又尝试了一下，重新配了一个虚拟环境，在原先提供的预训练权重下，跑voc是可以出现预测框的，
但是，在不使用预训练权重，进行训练之后就没有训练框了（是不是因为迭代次数过少loss过高导致的，毕竟网络没有返回预测结果，故无法生成预测框）

**Comment by theDeep1nteresting** [comment]
同样的操作，区别只在于 streetsjpg
加载model_data/yolox_s.pth进行训练——logs/ep001-loss5.062-val_loss3.771.pth——有图有框
不加载model_data/yolox_s.pth进行训练——logs/ep003-loss10.661-val_loss10.623.pth——有图无框
头大T_T（感觉特征提取网络什么都没有学到，还是别的原因？）

**Comment by theDeep1nteresting** [comment]
我找旁边的同学要了他的YOLOv4模型（也是基于你的yolo改的），他对模型进行了修改，也没有加载你的预训练权重，训练了VOC的权重。
我将他的文件运行在我的电脑上，结果有图有框.......
环境没问题，代码没改动，到底是哪里出问题了呢？ 404

**Comment by theDeep1nteresting** [comment]
看了up的问题汇总，训练一晚上再看看效果

**Comment by theDeep1nteresting** [comment]
果然loss并不能代表map，还是训练的不够T_T'
end!

**Comment by bubbliiiing** [comment]
这，挺好的

**Comment by bubbliiiing** [comment]
一般来讲没有预训练效果会差很多，但是也不是完全没有效果，还是会有一定的效果的，但是loss要让他下来才行

**Comment by bubbliiiing** [comment]
预训练大部分情况下都是要使用的

**Comment by theDeep1nteresting** [comment]
哈哈，我又来咨询了
跑完了120个epoch，发现前50个冻结训练的epoch，对map基本没有提升
后70个epoch，
map从 ：    epoch50：map1%——>epoch60：map48%——>epoch70：map39% —
                    —>epoch115：map63%——>epoch120：map55%
总体是提升的，但是训练过程是波动的
想问一下，如果要自己训练voc，不用预权值大概要多少epoch可以到voc数据集map90%呢

**Comment by bubbliiiing** [comment]
你重新下一下库，看一下里面的注释

**Comment by theDeep1nteresting** [comment]
好哒

**Comment by WechangingK** [comment]
我也遇到了相同的问题，怎么解决的呢？
