### ISSUE TITLE
原版YOLOX中好像并没有downsample模块

### ISSUE THREAD

**Issue by lunaWU628** [bubbliiiing/yolox-pytorch#130]
原版YOLOX在Neck部分，好像并没有downsample模块，我也看了其他人画的YOLOX网络结构，也没有downsample

而我看您写的代码以及网络结构中都加上了downsample，请问这是为什么呢？
![image](https://user-images.githubusercontent.com/90367095/223012757-4f743d8a-6591-42fd-bbe3-97022c7caf6e.png)

![image](https://user-images.githubusercontent.com/90367095/223012819-d89d31ef-8170-428d-b955-375be8c5ad26.png)

**Comment by bubbliiiing** [comment]
鹅，只是没画出来，它也是存在的

**Comment by ArFFy1314** [comment]
这里实际上是一个CBS模块，kernel=3，stride=2，padding=1，out_channel=256or512,功能与下采样是相同的，而且还提取了融合完特征的小目标。B导可能觉得这样画更容易理解一点，毕竟左边上采样，右边下采样，才是加强特征网络融合。

**Comment by bubbliiiing** [comment]
额0 0
加油啊

**Comment by bubbliiiing** [comment]
额0 0
加油啊

**Comment by lunaWU628** [comment]
> 

谢谢解答
