### ISSUE TITLE
训练自己数据，MAP出现问题

### ISSUE THREAD

**Issue by theDeep1nteresting** [bubbliiiing/yolox-pytorch#14]
hi，博主
关于训练自己的数据集，
已经将对应格式的文件放到相同路径下的文件夹内，新添了自己的cls.txt。训练完成后，也有训练框。
但是，测试map时，仍然有原voc的测试类别，想问一下这是什么情况呢？
（ classes_path    = 'model_data/fire.txt'已经就改）

**Comment by theDeep1nteresting** [comment]
问题已解决：
map_out 文件下继承了之前训练的数据，将map_out文件夹删去就ok了

**Comment by bubbliiiing** [comment]
嗯是的

**Comment by bubbliiiing** [comment]
你B站也问了吧
