### ISSUE TITLE
使用训练好的模型进行预测，发现没有检测到任何目标

### ISSUE THREAD

**Issue by PyAllegro** [bubbliiiing/yolox-pytorch#18]
在利用自己的数据集训练好模型后，进行预测发现img_out中的图片没有检测到任何目标，后来把NMS打印出来发现确实没有筛选出任何目标框，但训练完成后模型收敛正常，进行预测时已同步更改了训练好的模型和标签名文件路径。还麻烦帮忙分析下是什么原因导致这种异常现象的，非常感谢！
![train](https://user-images.githubusercontent.com/38966664/137611750-0cdb5eaa-b286-48d2-b7cf-09472c783228.png)
![NMS_out](https://user-images.githubusercontent.com/38966664/137611754-f3804c97-93ea-48b9-88a6-8bb7cc28cd9f.png)

**Comment by PyAllegro** [comment]
相比使用官方的YOLOX-S进行预测的结果，自己训练好的YOLOX-S进行预测时，模型输出的类概率中有很多都是0.5，有点搞不懂是什么原因
![image](https://user-images.githubusercontent.com/38966664/137623624-628c3a43-c0d4-4bb8-8649-fc37ad0854f0.png)

**Comment by PyAllegro** [comment]
谢谢回复，我再次看了下Issues中的问题汇总，但是没有发现和我遇到的类似的问题的解决方法。

**Comment by ZSN1414** [comment]
我想问一下，这个问题解决了吗？

**Comment by PyAllegro** [comment]
后面没有去弄了，换了别的YOLOX
