### ISSUE TITLE
在使用YOLOX模型 对视频进行预测时，出现了如下错误

### ISSUE THREAD

**Issue by MasterMiao919** [bubbliiiing/yolox-pytorch#29]
在使用YOLOX模型 对视频进行预测时，出现了如下错误：
cv2.error: OpenCV(4.5.4-dev) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
![image](https://user-images.githubusercontent.com/40556296/140012647-1a8a7afb-61fc-4ae4-9148-c3b60abf33ee.png)

请问如何解决呀？

**Comment by bubbliiiing** [comment]
路径错了可能

**Comment by MasterMiao919** [comment]
我的预测视频路径设置是这样的：
![image](https://user-images.githubusercontent.com/40556296/140299431-a39f14c3-78cc-4d28-93de-a59d793db051.png)

这样子设置正确吗？

**Comment by bubbliiiing** [comment]
这样看着正确诶……还有报错吗

**Comment by MasterMiao919** [comment]
有的呀，还是一样报错



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月9日(周二) 凌晨0:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bubbliiiing/yolox-pytorch] 在使用YOLOX模型 对视频进行预测时，出现了如下错误 (Issue #29)




 
这样看着正确诶……还有报错吗
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bubbliiiing** [comment]
你确认输入的视频是可以看的吗

**Comment by MasterMiao919** [comment]
对的，就是我预测完准备执行保存操作就出错了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月9日(周二) 上午9:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bubbliiiing/yolox-pytorch] 在使用YOLOX模型 对视频进行预测时，出现了如下错误 (Issue #29)




 
你确认输入的视频是可以看的吗
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bubbliiiing** [comment]
噢噢。你根目录下不是有predict.mp4吗
