### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by Kaiwen6** [bubbliiiing/yolox-pytorch#33]
泡泡哥，请问不使用预训练，从头开始训的话，学习率和优化器选择那个合适，我用了yolox-s将VOC训练集用来训练，大概150epoch后损失收敛，但测试集最后map只有30%不到。。。（我搞了了一个新结构，打算对比一下，所以需要从头开始。）

**Comment by bubbliiiing** [comment]
先按注释的方式从头开始训练
然后你发现效果差的话，再看一下注释……
