### ISSUE TITLE
loss为0

### ISSUE THREAD

**Issue by Him-wen** [bubbliiiing/yolox-pytorch#62]
作者，loss 跑了几个epoch就变成了0 之后全是0，这是为什么呢？

**Comment by Him-wen** [comment]
Efficientnet-Yolo3 也是如此，没几个epoch开始就 loss全为0

**Comment by Him-wen** [comment]
<img width="282" alt="截屏2022-03-29 上午10 21 31" src="https://user-images.githubusercontent.com/24501320/160519890-42326ea5-d295-475f-ba25-2bc300113b2a.png">

**Comment by mepleleo** [comment]
我跑yolov4的时候也这样，这是啥问题？

**Comment by bubbliiiing** [comment]
没有目标信息
