### ISSUE TITLE
中断了训练怎么继续resume继续训练啊

### ISSUE THREAD

**Issue by SSTato** [bubbliiiing/yolox-pytorch#64]
我在中断训练后将初始权重设置为中断训练最后的权重，发现并不能resume，只是将最后的训练权重当做预训练权重继续训练，训练了半天效果和中断时的差不多。请问怎么才能resume继续训练。

![image](https://user-images.githubusercontent.com/93987794/161196779-ce8280f7-9d4f-45f1-a6a1-760a85d1f1f2.png)
图片中从39轮开始重新训练的

**Comment by bubbliiiing** [comment]
你的epoch什么的都改了吗

**Comment by SSTato** [comment]
> 你的时代什么都改了

改成从39轮开始

**Comment by bubbliiiing** [comment]
应该是学习率太大了那时候……
我没有保存optimizer的信息，是比较伤的
